### ISSUE TITLE
Is it possible to add auth http headers in options?

### ISSUE THREAD

**Issue by danieldai** [samouss/react-hooks-sse#239]
Is it possible to add auth http headers in options?

**Comment by samouss** [comment]
The specification that defines the Server-Sent Events does not allow the possibility to add extra headers to the request. The only option supported is [`withCredentials`](https://developer.mozilla.org/en-US/docs/Web/API/EventSource/EventSource#Syntax). Internally the lib uses the `EventSource` constructor by default.

What I could do though is to let the user provide its own implementation of the [`EventSource`](https://www.w3.org/TR/eventsource/#the-eventsource-interface) interface. There is some [polyfill](https://github.com/Yaffle/EventSource#custom-headers) that implement this behaviour.

**Comment by danieldai** [comment]
Thanks for that, I will try with the polyfill
