### ISSUE TITLE
Need proper documentation for supplying custom source

### ISSUE THREAD

**Issue by amitkumarc2fo** [samouss/react-hooks-sse#451]
It would be nice to have an example on how to pass the `Authorization` header and API path when using `source` prop instead of `endpoint`

**Comment by Ponjimon** [comment]
Why have you closed this? The documentation is insufficient, I have no idea how to add a custom source just from the documentation

**Comment by samouss** [comment]
I'll give a try this week-end. I'll see how it goes and add a section in the README.
